version: '3.5'
services:
    python3:
        build: .
        container_name: 'md_api'
        working_dir: '/server'
        ports:
            - "$PORT"
        volumes:
            - ./server:/server
        networks:
            - proxy
        restart: always

networks:
    proxy:
        name: nginx_reverse_proxy
        #networks:
        #    nginx_reverse_proxy:
        #        external: true
