version: '3'
services:
    python3:
        build: .
        container_name: 'dev_mp3_api'
        working_dir: '/server'
        ports:
            - "$PORT"
        volumes:
            - ./server:/server
        networks:
            - nginx_reverse_proxy
        restart: always

networks:
    nginx_reverse_proxy:
        external: true
